const express = require("express")
const mongoose = require("mongoose")
const cors = require("cors")
const connect = require("./config/Connect")
const dotenv = require("dotenv")
const userRouter = require("./Controller/user.router")
const taskControl = require("./Controller/task.router")
const projectControl = require("./Controller/project.router")
const clientControl = require("./Controller/client.router")
const tagControl = require("./Controller/tag.router")
dotenv.config("./.env")
const PORT =process.env.PORT
console.log(PORT)

const server = express()
server.use(cors())
server.use(express.json())
server.get("/",async(req,res)=>{
    res.send("Welcome to my server")
})
server.use("/user",userRouter)
server.use("/task",taskControl)
server.use("/project",projectControl)
server.use("/client",clientControl)
server.use("/tag",tagControl)

server.listen(PORT,async()=>{
    await connect()
    console.log("Server started at port 8080")
})